export const mockBeneficiaries = [
  {
    id: "BEN001",
    name: "Ekaette Okon",
    stage: "Launch & Operations",
    progress: 72,
    location: "Calabar Municipal",
    lga: "Calabar Municipal",
    ventureType: "Boutique & Fashion",
    riskLevel: "low",
    email: "ekaette@example.com",
    businessName: "Ekaette's Fashion Hub",
    progressMetric: 72,
    fundReleased: 450000,
    nextMilestone: "Growth & Scaling",
  },
  {
    id: "BEN002",
    name: "Bassey Etim",
    stage: "Planning & Setup",
    progress: 38,
    location: "Calabar South",
    lga: "Calabar South",
    ventureType: "Poultry Farming",
    riskLevel: "medium",
    email: "bassey@example.com",
    businessName: "Bassey's Poultry Farm",
    progressMetric: 38,
    fundReleased: 300000,
    nextMilestone: "Launch & Operations",
  },
  {
    id: "BEN003",
    name: "Iniobong Archibong",
    stage: "Launch & Operations",
    progress: 88,
    location: "Odukpani",
    lga: "Odukpani",
    ventureType: "Cassava Processing",
    riskLevel: "low",
    email: "iniobong@example.com",
    businessName: "Iniobong Cassava Works",
    progressMetric: 88,
    fundReleased: 700000,
    nextMilestone: "Growth & Scaling",
  },
  {
    id: "BEN004",
    name: "Mfoniso Ekpo",
    stage: "Launch & Operations",
    progress: 62,
    location: "Akpabuyo",
    lga: "Akpabuyo",
    ventureType: "Mobile Phone Accessories Trading",
    riskLevel: "high",
    email: "mfoniso@example.com",
    businessName: "Mfoniso Mobile Tech",
    progressMetric: 62,
    fundReleased: 350000,
    nextMilestone: "Growth & Scaling",
  },
  {
    id: "BEN005",
    name: "Unwana Effiong",
    stage: "Growth & Scaling",
    progress: 92,
    location: "Calabar Municipal",
    lga: "Calabar Municipal",
    ventureType: "Food Processing & Catering",
    riskLevel: "low",
    email: "unwana@example.com",
    businessName: "Unwana's Food Delights",
    progressMetric: 92,
    fundReleased: 950000,
    nextMilestone: "Sustainability & Impact",
  },
  {
    id: "BEN006",
    name: "Aniefiok Asuquo",
    stage: "Planning & Setup",
    progress: 45,
    location: "Bakassi",
    lga: "Bakassi",
    ventureType: "Fishing & Seafood Trading",
    riskLevel: "medium",
    email: "aniefiok@example.com",
    businessName: "Aniefiok Seafood Enterprise",
    progressMetric: 45,
    fundReleased: 320000,
    nextMilestone: "Launch & Operations",
  },
  {
    id: "BEN007",
    name: "Eno-obong Inyang",
    stage: "Launch & Operations",
    progress: 75,
    location: "Calabar South",
    lga: "Calabar South",
    ventureType: "Arts & Crafts Production",
    riskLevel: "low",
    email: "eno@example.com",
    businessName: "Eno's Craft Studio",
    progressMetric: 75,
    fundReleased: 410000,
    nextMilestone: "Growth & Scaling",
  },
]

export const mockFundingData = [
  {
    id: "TRANCHE001",
    beneficiary: "Ekaette Okon",
    businessName: "Ekaette's Fashion Hub",
    totalAllocation: 1000000,
    released: 450000,
    pending: 550000,
    stage: "Launch & Operations",
    status: "on-track",
    nextRelease: 400000,
    lga: "Calabar Municipal",
    milestones: [
      { name: "Proof of Business Setup", amount: 300000, status: "completed" },
      { name: "Sales Records & Operations", amount: 400000, status: "in-progress" },
      { name: "Expansion Evidence", amount: 300000, status: "pending" },
    ],
  },
  {
    id: "TRANCHE002",
    beneficiary: "Bassey Etim",
    businessName: "Bassey's Poultry Farm",
    totalAllocation: 1000000,
    released: 300000,
    pending: 700000,
    stage: "Planning & Setup",
    status: "delayed",
    nextRelease: 400000,
    lga: "Calabar South",
    milestones: [
      { name: "Business Registration", amount: 300000, status: "completed" },
      { name: "Proof of Business Setup", amount: 400000, status: "pending" },
      { name: "Sales Records & Operations", amount: 300000, status: "pending" },
    ],
  },
  {
    id: "TRANCHE003",
    beneficiary: "Iniobong Archibong",
    businessName: "Iniobong Cassava Works",
    totalAllocation: 1000000,
    released: 700000,
    pending: 300000,
    stage: "Launch & Operations",
    status: "on-track",
    nextRelease: 300000,
    lga: "Odukpani",
    milestones: [
      { name: "Proof of Business Setup", amount: 300000, status: "completed" },
      { name: "Sales Records & Operations", amount: 400000, status: "completed" },
      { name: "Expansion Evidence", amount: 300000, status: "in-progress" },
    ],
  },
]



export const mockAIReports = [
  {
    id: "REPORT001",
    beneficiary: "Mfoniso Ekpo",
    businessName: "Mfoniso Mobile Tech",
    lga: "Akpabuyo",
    date: "2027-03-18",
    riskScore: 68,
    riskLevel: "high",
    summary: [
      "Delayed weekly operational reports submitted late",
      "Sales performance below projected targets",
      "Equipment maintenance costs running high",
      "Working capital management concerns noted",
    ],
    recommendations: [
      "Schedule follow-up meeting with beneficiary",
      "Review cash flow projections and expense tracking",
      "Provide business management support",
    ],
  },
  {
    id: "REPORT002",
    beneficiary: "Iniobong Archibong",
    businessName: "Iniobong Cassava Works",
    lga: "Odukpani",
    date: "2027-03-20",
    riskScore: 18,
    riskLevel: "low",
    summary: [
      "Strong progress in agricultural production",
      "Sales records well-maintained and growing",
      "Excellent engagement with local suppliers",
      "Community impact and job creation evident",
    ],
    recommendations: ["Continue current operational trajectory", "Begin exploration of market expansion opportunities"],
  },
  {
    id: "REPORT003",
    beneficiary: "Ekaette Okon",
    businessName: "Ekaette's Fashion Hub",
    lga: "Calabar Municipal",
    date: "2027-03-19",
    riskScore: 35,
    riskLevel: "low",
    summary: [
      "Consistent sales growth and customer retention",
      "Quality inventory management and stock records",
      "Good financial discipline and reporting",
      "Customer acquisition strategy performing well",
    ],
    recommendations: ["Explore seasonal marketing campaigns", "Plan expansion to adjacent retail locations"],
  },
]

export const mockAlerts = [
  {
    id: "ALERT001",
    type: "deadline-missed",
    beneficiary: "Iniobong Archibong",
    location: "Odukpani",
    message: "Missed weekly operational update submission",
    severity: "high",
    date: "2027-03-10",
  },
  {
    id: "ALERT002",
    type: "budget-overrun",
    beneficiary: "Mfoniso Ekpo",
    location: "Akpabuyo",
    message: "Equipment purchases exceeded approved budget by 18%",
    severity: "high",
    date: "2027-03-12",
  },
  {
    id: "ALERT003",
    type: "milestone-delay",
    beneficiary: "Bassey Etim",
    location: "Calabar South",
    message: "Business setup milestone delayed by 3 weeks",
    severity: "medium",
    date: "2027-03-08",
  },
  {
    id: "ALERT004",
    type: "compliance-gap",
    beneficiary: "Aniefiok Asuquo",
    location: "Bakassi",
    message: "Missing business registration documentation",
    severity: "medium",
    date: "2027-03-05",
  },
]

export const mockAnalytics = {
  totalBeneficiaries: 67,
  activeFunding: 23,
  totalFundsAllocated: 67000000,
  totalFundsReleased: 34200000,
  avgProgressRate: 64,
  complianceRate: 88,
  demographics: [
    { label: "Male", value: 42 },
    { label: "Female", value: 25 },
  ],
  lgas: [
    { name: "Calabar Municipal", count: 18 },
    { name: "Calabar South", count: 15 },
    { name: "Odukpani", count: 12 },
    { name: "Akpabuyo", count: 11 },
    { name: "Bakassi", count: 11 },
  ],
  ventureTypes: [
    { type: "Fashion & Retail", percentage: 22 },
    { type: "Agriculture & Farming", percentage: 28 },
    { type: "Food Processing", percentage: 18 },
    { type: "Trading & Wholesale", percentage: 16 },
    { type: "Crafts & Tourism", percentage: 16 },
  ],
  fundReleaseTrend: [
    { month: "Jan", amount: 4200000 },
    { month: "Feb", amount: 5100000 },
    { month: "Mar", amount: 6800000 },
    { month: "Apr", amount: 7200000 },
    { month: "May", amount: 5900000 },
    { month: "Jun", amount: 5000000 },
  ],
  stageDistribution: [
    { stage: "Planning & Setup", percentage: 18 },
    { stage: "Launch & Operations", percentage: 52 },
    { stage: "Growth & Scaling", percentage: 22 },
    { stage: "Sustainability & Impact", percentage: 8 },
  ],
}
